kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: management
    component: cluster-api
  name: cluster-api-authx-config
  namespace: __NPH_NAMESPACE
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE, APPCLUSTEROPS
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/cluster_api.Conductor/UpdateDeploymentFragmentStatus":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.Conductor/UpdateServiceStatus":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.NetworkManager/AuthorizeMember":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.NetworkManager/RegisterInboundServiceProxy":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.NetworkManager/RegisterOutboundProxy":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.DeviceManager/RegisterLatency":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.DeviceManager/GetDeviceGroupSecret":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.ClusterWatcherMaster/AddClusterInfo":{"must":["APPCLUSTEROPS"]},
       "/cluster_api.ConnectivityChecker/ClusterAlive":{"must":["APPCLUSTEROPS"]}
     }
    }