###
# Cluster API
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: cluster-api
  name: cluster-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: cluster-api
  template:
    metadata:
      labels:
        cluster: management
        component: cluster-api
    spec:
      volumes:
      - name: authx-config
        configMap:
          name: cluster-api-authx-config
      containers:
      - name: cluster-api
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/cluster-api:__NPH_VERSION
        imagePullPolicy: Always
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: authx-secret
              key: secret
        volumeMounts:
        - name: authx-config
          mountPath: "/nalej/config"
          readOnly: true
        args:
        - "run"
        - "--debug"
        - "--networkManagerAddress=network-manager.__NPH_NAMESPACE:8000"
        - "--conductorAddress=conductor.__NPH_NAMESPACE:5000"
        - "--deviceManagerAddress=device-manager.__NPH_NAMESPACE:6010"
        - "--authHeader=authorization"
        - "--authSecret=$(AUTH_SECRET)"
        - "--authConfigPath=/nalej/config/authx-config.json"
        - "--authxAddress=authx.__NPH_NAMESPACE:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
