###
# Cluster API
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: cluster-api
  name: cluster-api
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: cluster-api
  template:
    metadata:
      labels:
        cluster: management
        component: cluster-api
    spec:
      volumes:
      - name: authx-config
        configMap:
          name: cluster-api-authx-config
      containers:
      - name: cluster-api
        image: nalejregistry.azurecr.io/nalej/cluster-api:VERSION
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: authx-secret
              key: secret
        volumeMounts:
        - name: authx-config
          mountPath: "/nalej/config"
          readOnly: true
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--authHeader=authorization"
        - "--authSecret=$(AUTH_SECRET)"
        - "--authConfigPath=/nalej/config/authx-config.json"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
