kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: management
    component: cluster-api
  name: cluster-api-authx-config
  namespace: nalej
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE, APPCLUSTEROPS
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/cluster_api.Clusters/Ops":{"must":["APPCLUSTEROPS"]}
     }
    }
