[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/onsi/ginkgo"
    version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[constraint]]
    name="github.com/nalej/derrors"
    version="=v2.0.0"

[[constraint]]
    name="github.com/nalej/nalej-bus"
    version="=v0.4.0"

[[constraint]]
    name="github.com/nalej/grpc-authx-go"
    version="=v0.0.50"

[[constraint]]
    name="github.com/nalej/grpc-cluster-api-go"
    version="=v0.0.22"

[[constraint]]
    name="github.com/nalej/grpc-conductor-go"
    version="=v0.0.91"

[[constraint]]
    name="github.com/nalej/grpc-network-go"
    version="=v0.0.43"

[[constraint]]
    name="github.com/nalej/grpc-common-go"
    version="=v0.0.33"

[[constraint]]
    name="github.com/nalej/grpc-device-manager-go"
    version="=v0.0.9"

[[constraint]]
    name="github.com/nalej/authx"
    version="v0.2.0"

[[constraint]]
    name="github.com/nalej/grpc-bus-go"
    version="=v0.0.19"
